"""add topic notes and password reset tokens

Revision ID: 754218db8611
Revises: 
Create Date: 2026-09-27 11:34:38.309317
"""
from alembic import op
import sqlalchemy as sa


revision = '754218db8611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_progress', sa.Column('notes', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_progress', 'notes')
    # ### end Alembic commands ###
